# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        echo "Checking if requirements.txt exists..."
        ls -la  # Debug: List files to ensure requirements.txt is present
        if [ -f requirements.txt ]; then 
          echo "Installing dependencies from requirements.txt"
          cat requirements.txt  # Debug: Show contents of requirements.txt
          pip install -r requirements.txt
        else 
          echo "requirements.txt not found!"
          exit 1  # Stop the workflow if requirements.txt is missing
        fi  # ✅ Correctly closing the if statement
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        ls -R
        python -m pytest --import-mode=append tests/ --maxfail=5 --tb=short
